# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Equity-Bank-Assessment' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Equity-Bank-Assessment

  target 'Equity-Bank-AssessmentTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Equity-Bank-AssessmentUITests' do
    # Pods for testing
  end

end
